### ISSUE TITLE
[Bug]: MSRV with latest half@2.3 is now on 1.70

### ISSUE THREAD

**Issue by elpiel** [enarx/ciborium#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Although MSRV is set for `-ll` because of the upgrade of half@2.3 MSRV is now 1.70
``

### Expected Behaviour

MSRV 1.58 should be respected even with optional dependency `half`

### Environment Information

https://github.com/AeroRust/nmea/actions/runs/7723182617/job/21052735785?pr=118

**Comment by rjzak** [comment]
We're using `half` v2.2, which is has a MSRV of 1.58. https://github.com/starkat99/half-rs/tree/08a03fd47b9241024e68bf375f2a7a84287bf481.

Maybe you're asking for `half` to be bumped, along with the MSRV?

Looking at your `Cargo.toml`, it seems your project is pulling in `half` 2.3, which is odd since our `Cargo.toml` specified 2.2. So maybe we need `=2.2` to prevent the compiler from picking a newer version. But just updating dependencies is probably better :)

**Comment by elpiel** [comment]
Yes, what specifying "2.2" means is "^2.2" which means that minor versions are upgraded (i.e. to 2.3).
As for my Cargo.toml, I don't actually depend on ciborium but `criterion` and I had to split the criterion benchmark to separate crate to avoid bumping MSRV every time a dependency of criterion bumps it.

**Comment by rjzak** [comment]
Closed via https://github.com/enarx/ciborium/pull/103
