### ISSUE TITLE
Possible error round tripping?

### ISSUE THREAD

**Issue by 5225225** [enarx/ciborium#31]
I'm fuzzing this crate with a harness that checks that decoded objects, when encoded and decoded again, become the original object.

Looks like

```rust
#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    if let Ok(v) = ciborium::de::from_reader(data) {
        let old: ciborium::value::Value = v;
        let mut writer = Vec::new();
        ciborium::ser::into_writer(&old, &mut writer);
        let new: ciborium::value::Value =
            ciborium::de::from_reader(&writer[..]).expect("round trip");
        if old != old {
            // contains NaN, can't compare.
            return;
        }
        eprintln!("old: {data:x?}");
        eprintln!("new: {writer:x?}");
        assert_eq!(old, new);
    }
    let _: Result<ciborium::value::Value, _> = ciborium::de::from_reader(data);
});
```

And it found this case

```rust
old: [195, 95, 255]
new: [195, 64]
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Tag(3, Bytes([]))`,
 right: `Integer(Integer(-1))`', fuzz_targets/fuzz_target_1.rs:17:9
```

Is the harness correct here?

**Comment by ahmedcharles** [comment]
If you use https://cbor.me it will show (your harness would make it easier if it printed values in hex):

```
# CBOR sequence with 2 elements
C3       # tag(3)
   5F    # bytes(*)
      FF # primitive(*)
C3     # tag(3)
   40  # bytes(0)
       # ""
```

What's going on here is that the old is an empty byte string using indefinite length form, while the new is an empty byte string using fixed length form. Tag 3 means a negative bignum, which is interpreted as `-1 - n` where `n` is the value of the byte string interpreted as an unsigned integer in network byte order, where empty strings are `0`.

Given that `Value` doesn't distinguish which form was originally used, it can't preserve indefinite length forms, so this test harness isn't going to work overall.

That said, `Value` should recognize both as either `Integer(Integer(-1))` or `Tag(3, Bytes([]))`, consistently.

The issue is that https://github.com/enarx/ciborium/blob/main/ciborium/src/de/mod.rs#L167 does not correctly handle indefinite length byte strings.
